import type { SimulationResponse } from "../types/simulation";

export const fallbackSimulation: SimulationResponse = {
  product: "tomato",
  route: "Optimal Cold Chain",
  risk_level: "MEDIUM",
  risk_pressure: { min: 38, max: 46, unit: "index" },
  remaining_quality: { min: 66, max: 72, unit: "%" },
  estimated_shelf_life_range: { min: 16, max: 21, unit: "days" },
  estimated_loss_percentage: { min: 28, max: 34, unit: "%" },
  estimated_loss_value: { min: 700, max: 850, unit: "USD" },
  potential_savings_value: { min: 180, max: 260, unit: "USD" },
  logistics_stress: { min: 34, max: 42, unit: "index" },
  microbial_reduction_index: { min: 34, max: 42, unit: "index" },
  confidence: "MEDIUM",
  recommendations: ["scenario_within_operational_window", "adjust_humidity", "reduce_logistics_stress"],
  cold_chain_alert: null,
  digital_twin_summary: "digital_twin_batch_transport",
  model_notes: [
    "composite_quality_index",
    "dynamic_k_logistics_stress",
    "relative_risk_not_industrial_prediction",
    "literature_inspired_parameters",
    "ranges_include_operational_uncertainty",
  ],
  quality_curve: Array.from({ length: 28 }, (_, day) => ({
    day,
    irradiated: Math.max(100 * Math.exp(-0.026 * day), 24),
    irradiated_low: Math.max(100 * Math.exp(-0.026 * day) - 4.5, 24),
    irradiated_high: Math.min(100 * Math.exp(-0.026 * day) + 4.5, 100),
    non_irradiated: Math.max(100 * Math.exp(-0.042 * day), 24),
    cold_chain_event: day <= 1,
    delay_event: day === 2,
    thermal_event: day === 0,
    storage_event: day >= 4 && day <= 5,
  })),
};
